server:
  port: 9999
spring:
  application:
    name: reservation-client
  cloud:
    config:
      uri: http://localhost:8888
      profile: default
    stream:
      bindings:
        output:
          group: reservations-group
          destination: reservations
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}