server:
  port: 8040
spring:
  application:
    name: zuul-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#zuul:
#  routes:
#    blog:
#        path: /ymq/**
#        url: http://www.ymq.io/about
zuul:
  routes:
    api:
        path: /home
        serviceId: eureka-provider