server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      uri: http://localhost:8888
      server:
        git:
#          uri: https://github.com/ShawyerPeng/spring-cloud-config-repo
#          search-paths: spring-cloud-config-repo
          default-label: master
          uri: file:C://Users/ShawyerPeng/Desktop/spring-cloud-config-repo
          # search-paths: config-server/config
          # username=xxx
          # password=xxx
      label: master
      profile: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}